version: '3.5'
services:
    app_container:
        container_name: application
        build:
            context: .
            args:
                JAR_FILE: ${JAR_FILE}
            dockerfile: Dockerfile
        image: rest-api-application
        ports:
            - 8989:8000
        env_file:
            - .env
        restart: on-failure
        networks:
          - backend  
        depends_on:
            - "db_container"

    db_container:
        container_name: database
        image: 'postgres:10-alpine'
        env_file:
            - .env
        ports:
          - "5432:5432"
        networks:
          - backend  
          
networks:
  backend:
    driver: bridge